// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KongaTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createUserwithvalidemail() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Login / Signup")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("Adebayo");
    driver.findElement(By.id("lastname")).sendKeys("Ifedayo");
    driver.findElement(By.id("email")).sendKeys("adebayo1405@gmail.com");
    driver.findElement(By.id("phone")).sendKeys("08035151764");
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).sendKeys("Paswword1234");
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    driver.findElement(By.id("pin")).click();
    driver.findElement(By.id("pin")).sendKeys("5791");
    driver.findElement(By.cssSelector(".\\_83d7e_2rg5_")).click();
    driver.close();
  }
  @Test
  public void loginwithavalidemail() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Login / Signup")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("username")).sendKeys("adebayo1405@gmail.com");
    driver.findElement(By.id("password")).sendKeys("Paswword1234");
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.close();
  }
  @Test
  public void loginwithpasswordlessthan6characters() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.linkText("Login / Signup")).click();
    driver.findElement(By.id("username")).sendKeys("adebayo1405@gmail.com");
    driver.findElement(By.id("password")).sendKeys("Paswword1234");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Pasww");
    driver.findElement(By.cssSelector(".\\_0a08a_3czMG")).click();
    driver.findElement(By.cssSelector(".\\_41d61_2xTI6")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(4)")).getText(), is("The password must be at least 6 characters"));
    driver.close();
  }
  @Test
  public void loginwithwrongemail() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_3e6ae_Emfkt"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.linkText("Login / Signup")).click();
    driver.findElement(By.id("username")).sendKeys("adebayo1405@gmail.com");
    driver.findElement(By.id("password")).sendKeys("Paswword1234");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("adebayo145@gmail.com");
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    driver.findElement(By.cssSelector(".\\_0a76d_2_hrl:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).getText(), is("The username or password you have entered is incorrect. Please try again."));
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > span")).click();
    driver.close();
  }
  @Test
  public void loginwithwrongpassword() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.linkText("Login / Signup")).click();
    driver.findElement(By.id("username")).sendKeys("adebayo1405@gmail.com");
    driver.findElement(By.id("password")).sendKeys("Paswword1234");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).click();
    {
      WebElement element = driver.findElement(By.id("password"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("password")).sendKeys("Ifedayo123456");
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_988cf_1aDdJ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).getText(), is("The username or password you have entered is incorrect. Please try again."));
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).getText(), is("The username or password you have entered is incorrect. Please try again."));
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > span")).click();
    driver.close();
  }
}
